# Generated by Django 6.0 on 2025-12-23 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astreoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zodiac',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zodiac',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
